#!/usr/bin/env node
/* ===========================================================================
   tools/build.mjs — zero-dependency build for "The Civil War".

   Assembles the single shippable civil_war_generals.html from:
       build/base.html         the FROZEN foundation (Classic + Modern 3D + all
                               run-h chunks + the T1 War-Department layer) — a
                               byte-for-byte snapshot, NEVER edited by the build.
     + src/<modules>           the grand-strategy (owner-mode) work, authored as
                               ordered modules listed in src/00-manifest.json.

   The modules are concatenated (in manifest order) and spliced BEFORE the unique
   engine-end anchor in base.html (same contract as the legacy splice tool), so the
   anchor stays terminal and the last-def-wins override discipline holds.

   GATE-BEFORE-WRITE: the assembled HTML is gated IN MEMORY (extract <script> →
   `node --check` parse → invalid-hex grep → function-collision check). The
   deliverable civil_war_generals.html is overwritten ONLY if every gate passes,
   so a broken build can never corrupt the shipped file. Empirical/GPU probes
   (bootprobe, t1probe, diag-classic) run separately AFTER a successful build.

   Usage:  node tools/build.mjs            # build + gate
           node tools/build.mjs --check    # gate the assembled output, do NOT write
   Exit:   0 ok · 2 parse fail · 3 invalid-hex · 4 collision · 5 structural · 1 internal
   No external deps — node:fs / node:path / node:child_process only.
   =========================================================================== */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const BASE = join(ROOT, 'build', 'base.html');
const SRC = join(ROOT, 'src');
const OUT = join(ROOT, 'civil_war_generals.html');
const MANIFEST = join(SRC, '00-manifest.json');
// Build the anchor token at runtime so this source never contains a second copy.
const MARKER = '/*__ENGINE' + '_END__*/';
const HEX_BOMB = /0x[0-9a-fA-F]*[g-z]/;            // invalid hex literal -> parse bomb
const checkOnly = process.argv.includes('--check');

function die(code, msg) { console.error('BUILD FAIL [' + code + '] ' + msg); process.exit(code); }

// ---- 1. load base + assert the splice anchor is present and UNIQUE ----
if (!existsSync(BASE)) die(5, 'missing build/base.html (snapshot the frozen foundation first)');
const base = readFileSync(BASE, 'utf8');
const idx = base.indexOf(MARKER), last = base.lastIndexOf(MARKER);
if (idx < 0) die(5, 'MARKER_MISSING in base.html');
if (idx !== last) die(5, 'MARKER_NOT_UNIQUE in base.html');

// ---- 2. read manifest, concat ordered modules (per-module hex fail-fast) ----
const man = JSON.parse(readFileSync(MANIFEST, 'utf8'));
const modules = man.modules || [];
const overrides = new Set(man.overrides || []);   // function names allowed to appear 2x (base + override)
const newFns = [];                                 // brand-new top-level functions this build adds

let inject = '\n/* ====================================================================\n'
  + '   GENERATED by tools/build.mjs — base.html + data/*.json + src/*.js. DO NOT\n'
  + '   EDIT THIS FILE DIRECTLY; edit build/base.html, data/, or src/ and rebuild.\n'
  + '   ==================================================================== */\n';

// ---- 2a. inject data/*.json as a single GAME_DATA global (data-driven; one source of truth) ----
const DATA = join(ROOT, 'data');
let dataKeys = [];
if (existsSync(DATA)) {
  const dfiles = readdirSync(DATA).filter(f => f.endsWith('.json')).sort();
  const parts = [];
  for (const f of dfiles) {
    const raw = readFileSync(join(DATA, f), 'utf8');
    try { JSON.parse(raw); } catch (e) { die(5, 'invalid JSON in data/' + f + ': ' + e.message); }
    if (HEX_BOMB.test(raw)) die(3, 'invalid-hex literal in data/' + f);
    const key = f.replace(/\.json$/, '');
    parts.push(JSON.stringify(key) + ': ' + raw.trim());
    dataKeys.push(key);
  }
  if (parts.length) inject += '\n/* ===== data (build-injected from data/*.json) ===== */\nvar GAME_DATA = {\n' + parts.join(',\n') + '\n};\n';
}

for (const f of modules) {
  const p = join(SRC, f);
  if (!existsSync(p)) die(5, 'manifest lists missing module: ' + f);
  const txt = readFileSync(p, 'utf8');
  if (HEX_BOMB.test(txt)) die(3, 'invalid-hex literal in module ' + f);
  // collect top-level `function NAME(` declarations this module introduces
  const re = /(^|\n)\s*function\s+([A-Za-z_$][\w$]*)\s*\(/g;
  let m; while ((m = re.exec(txt))) { if (!overrides.has(m[2])) newFns.push({ name: m[2], file: f }); }
  inject += '\n/* ===== module: ' + f + ' ===== */\n' + txt + '\n';
}

// ---- 3. assemble in memory (marker stays terminal) ----
const out = base.slice(0, idx) + inject + base.slice(idx);

// ---- 4. GATE the assembled output (in memory) ----
const so = out.indexOf('<script>'), sc = out.indexOf('</script>');
if (so < 0 || sc < 0 || sc < so) die(5, 'could not locate a single <script>..</script> pair');
const body = out.slice(so + '<script>'.length, sc);

// 4a. parse gate
const tmp = join(tmpdir(), 'gor_build_check.js');
writeFileSync(tmp, body);
const chk = spawnSync(process.execPath, ['--check', tmp], { encoding: 'utf8' });
if (chk.status !== 0) die(2, 'node --check failed:\n' + (chk.stderr || chk.stdout || '').trim());

// 4b. invalid-hex gate (whole script body)
if (HEX_BOMB.test(body)) die(3, 'invalid-hex literal in assembled <script>');

// 4c. collision gate — new functions must appear exactly once; overrides exactly twice
const countFn = (name) => {
  const r = new RegExp('(^|\\n)\\s*function\\s+' + name.replace(/[$]/g, '\\$') + '\\s*\\(', 'g');
  return (body.match(r) || []).length;
};
for (const { name, file } of newFns) {
  const n = countFn(name);
  if (n !== 1) die(4, 'collision: new function ' + name + ' (' + file + ') defined ' + n + 'x (expected 1; rename or add to manifest.overrides)');
}
for (const name of overrides) {
  const n = countFn(name);
  if (n !== 2) die(4, 'override ' + name + ' defined ' + n + 'x (expected 2: base + override)');
}

// ---- 5. report + write ----
const KB = (s) => (s.length / 1024).toFixed(1) + 'KB';
console.log('GATE OK · parse ✓ · hex ✓ · collision ✓');
console.log('  data:      GAME_DATA = {' + (dataKeys.join(', ') || '(none)') + '}');
console.log('  modules:   ' + modules.join(', '));
console.log('  new fns:   ' + (newFns.map(x => x.name).join(', ') || '(none)'));
console.log('  overrides: ' + ([...overrides].join(', ') || '(none)') + ' (2x each ✓)');
console.log('  base ' + KB(base) + ' + inject ' + KB(inject) + ' = out ' + KB(out));

if (checkOnly) { console.log('--check: gates passed, NOT writing ' + OUT.split('/').pop()); process.exit(0); }
writeFileSync(OUT, out);
console.log('WROTE ' + OUT.split('/').pop() + ' (' + KB(out) + ')');
console.log('NEXT: node tools/bootprobe.mjs && node tools/t1probe.mjs && node tools/diag-classic.mjs');
