#!/usr/bin/env node
/* ===========================================================================
   tools/build.mjs — zero-dependency build for "The Civil War".

   Assembles the single shippable civil_war_generals.html from:
       build/base.html         the FROZEN foundation (Classic + Modern 3D + all
                               run-h chunks + the T1 War-Department layer) — a
                               byte-for-byte snapshot, NEVER edited by the build.
     + src/<modules>           the grand-strategy (owner-mode) work, authored as
                               ordered modules listed in src/00-manifest.json.

   The modules are concatenated (in manifest order) and spliced BEFORE the unique
   engine-end anchor in base.html (same contract as the legacy splice tool), so the
   anchor stays terminal and the last-def-wins override discipline holds.

   GATE-BEFORE-WRITE: the assembled HTML is gated IN MEMORY (extract <script> →
   `node --check` parse → invalid-hex grep → function-collision check). The
   deliverable civil_war_generals.html is overwritten ONLY if every gate passes,
   so a broken build can never corrupt the shipped file. Empirical/GPU probes
   (bootprobe, t1probe, diag-classic) run separately AFTER a successful build.

   Usage:  node tools/build.mjs            # build + gate
           node tools/build.mjs --check    # gate the assembled output, do NOT write
   Exit:   0 ok · 2 parse fail · 3 invalid-hex · 4 collision · 5 structural · 1 internal
   No external deps — node:fs / node:path / node:child_process only.
   =========================================================================== */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const BASE = join(ROOT, 'build', 'base.html');
const SRC = join(ROOT, 'src');
const OUT = join(ROOT, 'civil_war_generals.html');
const MANIFEST = join(SRC, '00-manifest.json');
// Build the anchor token at runtime so this source never contains a second copy.
const MARKER = '/*__ENGINE' + '_END__*/';
const HEX_BOMB = /0x[0-9a-fA-F]*[g-zG-Z]/;         // invalid hex literal -> parse bomb (case-complete, D229)
const checkOnly = process.argv.includes('--check');

function die(code, msg) { console.error('BUILD FAIL [' + code + '] ' + msg); process.exit(code); }

// ---- 1. load base + assert the splice anchor is present and UNIQUE ----
if (!existsSync(BASE)) die(5, 'missing build/base.html (snapshot the frozen foundation first)');
const base = readFileSync(BASE, 'utf8');
const idx = base.indexOf(MARKER), last = base.lastIndexOf(MARKER);
if (idx < 0) die(5, 'MARKER_MISSING in base.html');
if (idx !== last) die(5, 'MARKER_NOT_UNIQUE in base.html');

// ---- 2. read manifest, concat ordered modules (per-module hex fail-fast) ----
const man = JSON.parse(readFileSync(MANIFEST, 'utf8'));
const modules = man.modules || [];
const overrides = new Set(man.overrides || []);   // function names allowed to appear 2x (base + override)
const newFns = [];                                 // brand-new top-level functions this build adds

let inject = '\n/* ====================================================================\n'
  + '   GENERATED by tools/build.mjs — base.html + data/*.json + src/*.js. DO NOT\n'
  + '   EDIT THIS FILE DIRECTLY; edit build/base.html, data/, or src/ and rebuild.\n'
  + '   ==================================================================== */\n';

// ---- 2a. inject data/*.json as a single GAME_DATA global (data-driven; one source of truth) ----
const DATA = join(ROOT, 'data');
let dataKeys = [];
if (existsSync(DATA)) {
  const dfiles = readdirSync(DATA).filter(f => f.endsWith('.json')).sort();
  const parts = [];
  for (const f of dfiles) {
    const raw = readFileSync(join(DATA, f), 'utf8');
    try { JSON.parse(raw); } catch (e) { die(5, 'invalid JSON in data/' + f + ': ' + e.message); }
    // mask data:-URL string content first (parity with the 4b assembled-body scan): base64 blobs
    // legitimately contain 0x..[g-z] runs, and JSON parseability is already proven above (D229/E31).
    if (HEX_BOMB.test(raw.replace(/"data:[^"]*"/g, '""'))) die(3, 'invalid-hex literal in data/' + f);
    const key = f.replace(/\.json$/, '');
    parts.push(JSON.stringify(key) + ': ' + raw.trim());
    dataKeys.push(key);
  }
  if (parts.length) inject += '\n/* ===== data (build-injected from data/*.json) ===== */\nvar GAME_DATA = {\n' + parts.join(',\n') + '\n};\n';
}

// ---- 2b. inject assets/embed/** as a single __ASSETS global (D71 H1 ingestion pipeline) ----
// The OFFLINE tier: every file under assets/embed/<category>/ (the small, compressed,
// licence-vetted PD media produced by tools/prep-embed-assets.mjs) is Base64-inlined as a
// data: URL keyed "<category>/<basename-no-ext>". This is what makes the single-file deliverable
// portable: the in-game photo layer prefers __ASSETS (always present, offline) and upgrades to the
// relative-path hi-res (assets/<category>/) only when the file is served beside the assets folder.
// A HARD budget cap fails the build if the embed blob ever runs away (e.g. an un-compressed category)
// so the single file can never balloon unseen; SOFT warns earlier. Bump deliberately + log when a new
// (Aaron-approved) media category lands.
const EMBED = join(ROOT, 'assets', 'embed');
const EMBED_SOFT = 1.5 * 1024 * 1024;     // warn beyond ~1.5MB raw
const EMBED_HARD = 3.0 * 1024 * 1024;     // FAIL beyond ~3.0MB raw (runaway guard; raise + log when footage/scenes land)
const MIME = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp',
               '.gif': 'image/gif', '.svg': 'image/svg+xml', '.mp4': 'video/mp4', '.webm': 'video/webm' };
let embedBytes = 0, embedCount = 0;
const embedCats = {};
if (existsSync(EMBED)) {
  const aparts = [];
  const seenKeys = new Map();   // __ASSETS key -> source file (dup-key collision gate)
  for (const cat of readdirSync(EMBED, { withFileTypes: true }).filter(d => d.isDirectory()).sort((a, b) => a.name < b.name ? -1 : 1)) {
    const cdir = join(EMBED, cat.name);
    // withFileTypes so a stray sub-DIRECTORY named like an asset (e.g. foo.jpg/) is skipped, not
    // readFileSync'd into an uncaught EISDIR crash (bug-hunt FINDER#2).
    for (const ent of readdirSync(cdir, { withFileTypes: true }).filter(e => e.isFile() && e.name[0] !== '.').sort((a, b) => a.name < b.name ? -1 : 1)) {
      const f = ent.name;
      const ext = (f.match(/\.[^.]+$/) || [''])[0].toLowerCase();
      const mime = MIME[ext];
      if (!mime) die(5, 'embed: unsupported asset type ' + cat.name + '/' + f + ' (extend MIME[] in build.mjs to allow it)');
      const key = cat.name + '/' + f.replace(/\.[^.]+$/, '');
      // two sources differing only by extension (lee.jpg + lee.png) would collide to one key; the
      // last would silently win. Fail loudly instead (bug-hunt FINDER#2).
      if (seenKeys.has(key)) die(5, 'embed: duplicate __ASSETS key "' + key + '" from ' + cat.name + '/' + f + ' (collides with ' + seenKeys.get(key) + ') — two source files differ only by extension; rename or remove one.');
      seenKeys.set(key, cat.name + '/' + f);
      const buf = readFileSync(join(cdir, f));
      embedBytes += buf.length; embedCount++;
      embedCats[cat.name] = (embedCats[cat.name] || 0) + 1;
      aparts.push(JSON.stringify(key) + ':"data:' + mime + ';base64,' + buf.toString('base64') + '"');
    }
  }
  if (embedBytes > EMBED_HARD) die(5, 'embed BUDGET: assets/embed/ is ' + (embedBytes / 1048576).toFixed(2) + 'MB raw, over the ' + (EMBED_HARD / 1048576).toFixed(1) + 'MB hard cap — compress harder (tools/prep-embed-assets.mjs) or raise EMBED_HARD deliberately (and log why).');
  if (embedBytes > EMBED_SOFT) console.warn('  [embed] WARNING: ' + (embedBytes / 1048576).toFixed(2) + 'MB raw embed tier, over the ' + (EMBED_SOFT / 1048576).toFixed(1) + 'MB soft budget — consider compressing the tier (tools/prep-embed-assets.mjs).');
  if (aparts.length) inject += '\n/* ===== embedded assets (build-injected from assets/embed/**; offline tier) ===== */\nvar __ASSETS = {\n' + aparts.join(',\n') + '\n};\n';
}
// guarantee the bare-name global always exists so modules can read it unconditionally (no embed dir → {})
if (embedCount === 0) inject += '\n/* ===== embedded assets: none on disk; declare the empty global ===== */\nvar __ASSETS = {};\n';

for (const f of modules) {
  const p = join(SRC, f);
  if (!existsSync(p)) die(5, 'manifest lists missing module: ' + f);
  const txt = readFileSync(p, 'utf8');
  if (HEX_BOMB.test(txt)) die(3, 'invalid-hex literal in module ' + f);
  // collect top-level `function NAME(` declarations this module introduces
  const re = /(^|\n)\s*(?:async\s+)?function\s*(?:\*\s*)?([A-Za-z_$][\w$]*)\s*\(/g;   // also match async/generator declarations (D229/E28)
  let m; while ((m = re.exec(txt))) { if (!overrides.has(m[2])) newFns.push({ name: m[2], file: f }); }
  inject += '\n/* ===== module: ' + f + ' ===== */\n' + txt + '\n';
}

// ---- 2c. manifest-completeness gate (D229/E29): every src/**/*.js on disk must be enrolled ----
{
  const onDisk = [];
  const walkSrc = (dir, prefix) => {
    for (const ent of readdirSync(dir, { withFileTypes: true })) {
      if (ent.isDirectory()) { walkSrc(join(dir, ent.name), prefix + ent.name + '/'); continue; }
      if (ent.isFile() && ent.name.endsWith('.js')) onDisk.push(prefix + ent.name);
    }
  };
  walkSrc(SRC, '');
  const listed = new Set(modules);
  const orphans = onDisk.filter(f => !listed.has(f));
  if (orphans.length) die(5, 'manifest-completeness: src file(s) on disk but not enrolled in 00-manifest.json (they would silently ship NOWHERE and be scanned by NO gate): ' + orphans.join(', '));
}

// ---- 2d. script-terminator gate (D229/E40): injected content must never contain an HTML script
// terminator/opener — out.indexOf('</script>') would otherwise resolve INSIDE the inject, truncating
// the parse gate's view and shipping a broken page. Fail fast instead of trusting luck. ----
{
  const SCRIPT_BOMB = /<\/script|<script|<!--/i;
  const sb = inject.match(SCRIPT_BOMB);
  if (sb) die(5, 'script-terminator: injected data/module content contains "' + sb[0] + '" — an inline <script> body may not contain a literal script terminator/opener or HTML comment-open; escape it (e.g. <\\/script) or remove it.');
}

// ---- 3. assemble in memory (marker stays terminal) ----
const out = base.slice(0, idx) + inject + base.slice(idx);

// ---- 4. GATE the assembled output (in memory) ----
const so = out.indexOf('<script>'), sc = out.indexOf('</script>');
if (so < 0 || sc < 0 || sc < so) die(5, 'could not locate a single <script>..</script> pair');
const body = out.slice(so + '<script>'.length, sc);

// 4a. parse gate
const tmp = join(tmpdir(), 'gor_build_check_' + process.pid + '_' + Date.now().toString(36) + '.js');
writeFileSync(tmp, body);
const chk = spawnSync(process.execPath, ['--check', tmp], { encoding: 'utf8' });
if (chk.status !== 0) die(2, 'node --check failed:\n' + (chk.stderr || chk.stdout || '').trim());

// 4b. invalid-hex gate (whole script body). The HEX_BOMB heuristic catches an invalid hex LITERAL
// (e.g. 0x1g) in CODE — which can never appear inside a "data:...;base64,..." string literal. The
// embedded-asset blob (__ASSETS, H1/D71) is megabytes of base64 string content that textually trips
// the naive pattern (a "0x"+hex+[g-z] run is near-certain in any large base64), so mask data: URL
// string literals before this scan. Parseability of the WHOLE body is already proven by 4a
// (node --check), so masking string CONTENT here loses no real coverage. (Also covers future video
// data: URLs for H2 footage.)
const hexScan = body.replace(/"data:[^"]*"/g, '""');
if (HEX_BOMB.test(hexScan)) die(3, 'invalid-hex literal in assembled <script>');

// 4c. collision gate — new functions must appear exactly once; overrides exactly twice
const countFn = (name) => {
  const r = new RegExp('(^|\\n)\\s*(?:async\\s+)?function\\s*(?:\\*\\s*)?' + name.replace(/[$]/g, '\\$') + '\\s*\\(', 'g');
  return (body.match(r) || []).length;
};
for (const { name, file } of newFns) {
  const n = countFn(name);
  if (n !== 1) die(4, 'collision: new function ' + name + ' (' + file + ') defined ' + n + 'x (expected 1; rename or add to manifest.overrides)');
}
for (const name of overrides) {
  const n = countFn(name);
  if (n !== 2) die(4, 'override ' + name + ' defined ' + n + 'x (expected 2: base + override)');
}

// 4d. NO-FUDGE OUTPUT WALL (D74/D94 R-3) — the rating / badge module may only READ unit fields and
// RETURN factors; it must NEVER write a casualty count, a winner, unit strength, or an out-of-band
// sev.* at resolution time (the scripted "higher rating => auto-win" hack). Enforced STRUCTURALLY so
// the invariant cannot be eroded by a later increment. The combat modules (T0 etc.) legitimately write
// these — the wall scopes to the rating/badge module(s), which exist only to seed inputs.
// D105 (bug-hunt): 35-command.js carries the STRATEGIC rating code now (the dev-trait reputation-shaping —
// cmdOnResolve / _cmdDevTrait / _cmdAttritionDrag), which also only seeds an INPUT (reputation) and must never
// write the scoreboard. It writes solely command state (reputation/seniority/capital/devTrack), none of which
// match the forbidden set, so scoping the same wall over it closes the no-fudge coverage gap.
const RATING_MODULES = ['tactical/T14-ratings.js', '35-command.js', 'tactical/T15-oob.js'];   // D106: T15-oob = the OOB-mapping read-out (pure read; scanned so a future edit can't add a scoreboard write unseen)
const NO_FUDGE_FORBIDDEN = [
  { re: /\b(cas|aCas|bCas)\s*(\+=|-=|=)(?!=)/, what: 'a casualty count (cas/aCas/bCas)' },
  { re: /\.victory\s*=(?!=)/, what: 'the victory result (.victory)' },
  { re: /\.men\s*(\+=|-=|=)(?!=)/, what: 'unit strength (.men)' },
  // D229/E00: the wall now also covers the CLASSIC engine's strength fields and the modern engine's
  // other live combat-power levers (morale is a ~40% melee multiplier; ammo gates fire) so a scanned
  // rating module can never force a result through an unguarded field name on either engine.
  { re: /\.(strength|maxStr)\s*(\+=|-=|=)(?!=)/, what: "Classic unit strength (.strength/.maxStr)" },
  { re: /\.(morale|maxMor)\s*(\+=|-=|=)(?!=)/, what: 'unit morale (.morale/.maxMor)' },
  { re: /\.ammo\s*(\+=|-=|=)(?!=)/, what: 'unit ammunition (.ammo)' },
  { re: /\bsev\.[A-Za-z_$][\w$]*\s*=(?!=)/, what: 'a severity lever (sev.*) out of band' },
  // D229/E30: receiver-agnostic lever guard — a one-line alias (var s=__FIELD.sev; s.attrition=…)
  // defeated the sev.-prefixed pattern; guard direct writes to the six lever NAMES on any receiver.
  { re: /\.(attrition|canister|supply|cmdShock|sight|veteran)\s*=(?!=)/, what: 'a severity lever by name on any receiver (aliasing)' },
  // bracket-notation variants — close the computed-member bypass (u["men"]=0 etc.) so the wall cannot be
  // eroded by a later increment writing the scoreboard via brackets (R-3 bug-hunt hardening). A full AST scan
  // would also catch aliasing; this fast textual pass covers the direct bracket forms.
  { re: /\[\s*['"](?:men|cas|aCas|bCas|victory)['"]\s*\]\s*(\+=|-=|=)(?!=)/, what: 'a scoreboard field via bracket notation (["men"]/["victory"]/["cas"]…)' },
  { re: /\bsev\s*\[\s*['"][^'"]+['"]\s*\]\s*(\+=|-=|=)(?!=)/, what: 'a severity lever via bracket notation (sev["…"])' },
];
for (const rm of RATING_MODULES) {
  const rp = join(SRC, rm);
  if (!existsSync(rp)) continue;
  const rsrc = readFileSync(rp, 'utf8');
  for (const f of NO_FUDGE_FORBIDDEN) {
    const m = rsrc.match(f.re);
    if (m) die(5, 'no-fudge OUTPUT-WALL: ' + rm + ' writes ' + f.what + ' ("' + m[0].trim() + '") — the rating/badge layer may only SEED inputs + RETURN factors, never write the scoreboard at resolution time (D74/D94).');
  }
}

// 4e. CITATION-PROVENANCE GATE (D92/D103) — the citation-grade, anti-Lost-Cause non-negotiable enforced
// STRUCTURALLY: any record stamped prov/provenance:"Verified" MUST carry >=2 sources. Honest history means
// an authored claim either has >=2 independent citations (Verified) or is downgraded to Inferred/Disputed —
// never a "Verified" stamp resting on 0-1 sources. Scans every data/*.json recursively so the rule cannot be
// eroded by a later record anywhere in the catalog (mirrors the 4d no-fudge wall: a non-negotiable made
// un-erodable by the build itself).
{
  const offenders = [];
  const SRC_KEYS = ['sources', 'src'];
  const walk = (node, file, trail) => {
    if (Array.isArray(node)) { node.forEach((v, i) => walk(v, file, trail + '[' + i + ']')); return; }
    if (node && typeof node === 'object') {
      // match BOTH keys independently (so an Inferred `prov` can't mask a Verified `provenance`), and
      // normalize trim+case so a bare stamp of "Verified " / "verified" / "VERIFIED" cannot evade. The
      // long descriptive forms ("Verified specs (…)", "Verified (high) — …") trim-lowercase to something
      // other than exactly "verified", so they stay out of the structured-source gate by design (their
      // citations live inline in the prose) — R-6 bug-hunt hardening, D103.
      const norm = (v) => (typeof v === 'string' ? v.trim().toLowerCase() : '');
      const isVerified = norm(node.prov) === 'verified' || norm(node.provenance) === 'verified';
      if (isVerified) {
        let sc = 0;
        // D229/E14: count only DISTINCT, non-empty source entries (a Verified stamp resting on
        // ["McPherson","McPherson"] or ["",""] is 1 or 0 real citations, not 2) — matching gate 4f's rigor.
        for (const k of SRC_KEYS) {
          if (Array.isArray(node[k])) {
            const seenSrc = new Set();
            for (const s of node[k]) {
              const skey = (typeof s === 'string' ? s : JSON.stringify(s)).replace(/\s+/g, ' ').trim().toLowerCase();
              if (skey && skey !== '{}' && skey !== 'null') seenSrc.add(skey);
            }
            sc = seenSrc.size; break;
          }
        }
        if (sc < 2) {
          const id = node.key || node.name || node.id || node.label || trail || '(record)';
          offenders.push(file + ' :: ' + id + ' (Verified, ' + sc + ' source' + (sc === 1 ? '' : 's') + ')');
        }
      }
      for (const k in node) walk(node[k], file, trail ? trail + '.' + k : k);
    }
  };
  if (existsSync(DATA)) {
    for (const f of readdirSync(DATA).filter(f => f.endsWith('.json')).sort()) {
      let j; try { j = JSON.parse(readFileSync(join(DATA, f), 'utf8')); } catch (e) { continue; } // JSON already gated in 2a
      walk(j, 'data/' + f, '');
    }
  }
  if (offenders.length) die(5, 'citation-provenance: ' + offenders.length + ' record(s) stamped "Verified" with <2 sources (the >=2-source non-negotiable, D92/D103) — add a second independent REAL source or downgrade prov to "Inferred"/"Disputed":\n  ' + offenders.join('\n  '));
}

// 4e-2. E74 (D430) DESCRIPTIVE-VERIFIED COVERAGE RATCHET — gate 4e deliberately skips the long
// descriptive forms ("Verified (high) — …", "Verified specs (…)", "Verified identity; …"), whose
// citations live inline in prose or in the committed spec packets. THE INHERITANCE RULE: a
// descriptive-Verified object is STRUCTURALLY covered when it, or its nearest ancestor (walking
// up to the file root), carries a sources/src array with >=2 distinct entries. Everything else is
// GRANDFATHERED at the exact per-file baseline below (123 objects at D430) — the blind spot may
// never grow: a NEW descriptive-Verified object without structured own/ancestor sources fails the
// build, and any migration that shrinks a file's count must consciously lower its baseline here
// (documented history, the pin idiom). The full migration of the 123 into structured claim-local
// arrays / file-root registers is the recorded E74 design fork (DECISIONS D430) — this ratchet is
// containment + forward enforcement, NOT a substitute for that migration.
{
  // D433 migration history (the pin idiom): the D430 map pinned 123 grandfathered objects across
  // 28 files. The D433 E74-MIGRATE batches (D431 queue item 1) moved each file to structural
  // citation (battle-object/file-root register or per-object arrays lifted from the file's own
  // committed packets/prose) and lowered its entry to absence in the same commit:
  //   batch A (D433): antietam 8 -> 0, artillery 1 -> 0, diplomacy 6 -> 0,
  //                   manpower-teaching 6 -> 0, weapons 1 -> 0.
  const E74_BASELINE = {
    'bullrun.json': 3, 'cedar-creek.json': 3,
    'chancellorsville.json': 6, 'chattanooga.json': 9, 'chickamauga.json': 8,
    'cross-keys-port-republic.json': 3, 'elkhorn-tavern.json': 3,
    'five-forks.json': 1, 'fort-donelson.json': 4, 'franklin.json': 5, 'fredericksburg.json': 4,
    'gaines-mill.json': 1, 'gettysburg.json': 8, 'kennesaw.json': 5, 'malvern-hill.json': 6,
    'nashville.json': 8, 'new-market-heights.json': 3,
    'petersburg-assaults.json': 1, 'shiloh.json': 6, 'spotsylvania.json': 1,
    'stones-river.json': 3, 'vicksburg.json': 9, 'wilderness.json': 1
  };
  const SRC_KEYS2 = ['sources', 'src'];
  const norm2 = (v) => (typeof v === 'string' ? v.trim().toLowerCase() : '');
  const distinctCount = (arr) => {
    const seen = new Set();
    for (const s of arr || []) {
      const k = (typeof s === 'string' ? s : JSON.stringify(s)).replace(/\s+/g, ' ').trim().toLowerCase();
      if (k && k !== '{}' && k !== 'null') seen.add(k);
    }
    return seen.size;
  };
  const ownSrcCount = (n) => { for (const k of SRC_KEYS2) if (Array.isArray(n[k])) return distinctCount(n[k]); return -1; };
  const uncoveredByFile = {};
  const walk2 = (node, file, ancCovered, trail) => {
    if (Array.isArray(node)) { node.forEach((v, i) => walk2(v, file, ancCovered, trail + '[' + i + ']')); return; }
    if (node && typeof node === 'object') {
      const pv = [norm2(node.prov), norm2(node.provenance)];
      const isDescriptive = pv.some(p => p.startsWith('verified') && p !== 'verified');
      const own = ownSrcCount(node);
      if (isDescriptive && !(own >= 2 || ancCovered)) (uncoveredByFile[file] = uncoveredByFile[file] || []).push(trail || '(root)');
      const nextCovered = own >= 2 ? true : ancCovered;
      for (const k in node) walk2(node[k], file, nextCovered, trail ? trail + '.' + k : k);
    }
  };
  if (existsSync(DATA)) {
    for (const f of readdirSync(DATA).filter(f => f.endsWith('.json')).sort()) {
      let j; try { j = JSON.parse(readFileSync(join(DATA, f), 'utf8')); } catch (e) { continue; }
      walk2(j, f, false, '');
    }
  }
  const problems = [];
  const filesSeen = new Set([...Object.keys(E74_BASELINE), ...Object.keys(uncoveredByFile)]);
  for (const f of [...filesSeen].sort()) {
    const want = E74_BASELINE[f] || 0, got = (uncoveredByFile[f] || []).length;
    if (got > want) problems.push(f + ': ' + got + ' uncovered descriptive-Verified object(s), baseline ' + want + ' — new: ' + (uncoveredByFile[f] || []).join(', '));
    else if (got < want) problems.push(f + ': uncovered count dropped to ' + got + ' (baseline ' + want + ') — good; consciously lower its E74_BASELINE entry in the same commit (documented history)');
  }
  if (problems.length) die(5, 'E74 descriptive-Verified ratchet (D430): give the object (or an ancestor) a sources/src array with >=2 distinct REAL entries, downgrade the stamp, or consciously move the pinned baseline:\n  ' + problems.join('\n  '));
}

// 4f. SOLDIER'S STORY REPLACEMENT GATE (D152) — generated representative rows may be
// replaced later only by explicit citation-grade person records. The canonical data file
// is empty today; this gate makes future edits fail fast for malformed, prototype-polluted,
// under-cited, duplicate, or generated-mislabelled records before the playable HTML is written.
{
  const p = join(DATA, 'soldier-replacements.json');
  if (existsSync(p)) {
    const BAD = new Set(['__proto__', 'constructor', 'prototype', 'hasOwnProperty']);
    const ATTRS = ['tactical', 'command', 'initiative', 'resolve', 'discipline', 'marksmanship', 'vigor', 'charisma', 'aggression', 'grit', 'logistics', 'engineering', 'cavalry', 'artillery', 'political'];
    const errors = [];
    const plain = (o) => !!o && typeof o === 'object' && !Array.isArray(o);
    const cleanText = (v, max = 240) => String(v == null ? '' : v).replace(/\s+/g, ' ').trim().slice(0, max);
    const safePid = (v) => /^[A-Za-z0-9][A-Za-z0-9_.:-]{2,159}$/.test(cleanText(v, 160));
    const scanBadKeys = (node, trail = 'pack', depth = 0) => {
      if (depth > 12) { errors.push(trail + ' exceeds max nesting depth'); return; }
      if (Array.isArray(node)) { node.forEach((v, i) => scanBadKeys(v, trail + '[' + i + ']', depth + 1)); return; }
      if (!plain(node)) return;
      for (const k of Object.keys(node)) {
        if (BAD.has(k)) { errors.push(trail + '.' + k + ' uses a forbidden key'); continue; }
        scanBadKeys(node[k], trail ? trail + '.' + k : k, depth + 1);
      }
    };
    const sourceKey = (s) => cleanText((s.title || '') + '|' + (s.repository || '') + '|' + (s.locator || '') + '|' + (s.url || ''), 500).toLowerCase();
    const validateSources = (sources, label) => {
      const seen = new Set();
      if (!Array.isArray(sources)) { errors.push(label + '.sources must be an array'); return 0; }
      let count = 0;
      for (let i = 0; i < sources.length && count < 12; i++) {
        const src = sources[i];
        if (!plain(src)) { errors.push(label + '.sources[' + i + '] must be an object'); continue; }
        if (!(cleanText(src.title, 160) || cleanText(src.repository, 140))) errors.push(label + '.sources[' + i + '] needs title or repository');
        if (!(cleanText(src.locator, 140) || cleanText(src.url, 240))) errors.push(label + '.sources[' + i + '] needs locator or URL');
        const key = sourceKey(src);
        if (key && seen.has(key)) errors.push(label + '.sources[' + i + '] duplicates another source');
        if (key) seen.add(key);
        count++;
      }
      if (count < 2) errors.push(label + ' needs at least two independent sources');
      return count;
    };
    const validateRecord = (r, label, seenPid, seenReplace) => {
      if (!plain(r)) { errors.push(label + ' must be an object'); return; }
      const pid = cleanText(r.pid, 160), replacePid = cleanText(r.replacePid, 220);
      if (!safePid(pid)) errors.push(label + '.pid must be a stable safe id');
      if (pid.startsWith('ss:')) errors.push(label + '.pid must not use the generated ss: namespace');
      if (!replacePid.startsWith('ss:')) errors.push(label + '.replacePid must target a generated ss: slot');
      if (pid && seenPid.has(pid)) errors.push(label + '.pid duplicates ' + pid);
      if (replacePid && seenReplace.has(replacePid)) errors.push(label + '.replacePid duplicates ' + replacePid);
      if (pid) seenPid.add(pid);
      if (replacePid) seenReplace.add(replacePid);
      if (r.generated === true || r.source === 'Generated') errors.push(label + ' cannot mark a sourced replacement as generated');
      if (r.side !== 'US' && r.side !== 'CS') errors.push(label + '.side must be US or CS');
      if (!cleanText(r.name, 120) || /[<>]/.test(String(r.name || ''))) errors.push(label + '.name is required and must be plain text');
      if (!cleanText(r.rank, 80)) errors.push(label + '.rank is required');
      if (!['inf', 'art', 'cav'].includes(cleanText(r.branch || 'inf', 20))) errors.push(label + '.branch must be inf, art, or cav');
      if (typeof r.year !== 'number' || !Number.isFinite(r.year) || r.year < 1861 || r.year > 1865) errors.push(label + '.year must be 1861-1865');
      if (r.provenance !== 'Verified' && r.provenance !== 'Disputed') errors.push(label + '.provenance must be Verified or Disputed');
      if (r.provenance === 'Disputed' && !cleanText(r.disputeNote, 360)) errors.push(label + '.disputeNote is required for Disputed records');
      validateSources(r.sources, label);
      if (!plain(r.persona)) errors.push(label + '.persona must be an object with all rating attributes');
      else for (const a of ATTRS) if (typeof r.persona[a] !== 'number' || !Number.isFinite(r.persona[a]) || r.persona[a] < 0 || r.persona[a] > 100) errors.push(label + '.persona.' + a + ' must be a number from 0 to 100');
      if (!plain(r.team)) errors.push(label + '.team must be an object');
      else {
        const teamSide = r.team.side === 'US' || r.team.side === 'CS' ? r.team.side : r.side;
        if (teamSide !== r.side) errors.push(label + '.team.side must match record side');
        if (!cleanText(r.team.army, 120)) errors.push(label + '.team.army is required');
        if (!(cleanText(r.team.brigade, 120) || cleanText(r.team.regiment, 120) || cleanText(r.team.company, 40))) errors.push(label + '.team needs brigade, regiment, or company');
      }
      if (r.portrait != null) {
        if (!plain(r.portrait)) errors.push(label + '.portrait must be an object');
        else {
          const assetKey = cleanText(r.portrait.assetKey, 120);
          if (!/^portraits\/[A-Za-z0-9_.-]{3,80}$/.test(assetKey)) errors.push(label + '.portrait.assetKey must be an embedded portraits/<key>');
          if (!cleanText(r.portrait.alt, 180)) errors.push(label + '.portrait.alt is required');
          if (!cleanText(r.portrait.caption, 220)) errors.push(label + '.portrait.caption is required');
          if (!cleanText(r.portrait.credit, 120)) errors.push(label + '.portrait.credit is required');
          const url = cleanText(r.portrait.url, 240);
          if (url && !/^https?:\/\//.test(url)) errors.push(label + '.portrait.url must be http(s)');
        }
      }
    };
    const pack = JSON.parse(readFileSync(p, 'utf8'));
    scanBadKeys(pack);
    if (!plain(pack)) errors.push('pack must be a JSON object');
    if (pack.schema !== 'cw_soldier_replacements_v1') errors.push('schema must be cw_soldier_replacements_v1');
    if (!Array.isArray(pack.records)) errors.push('records must be an array');
    const seenPid = new Set(), seenReplace = new Set();
    if (Array.isArray(pack.records)) pack.records.forEach((r, i) => validateRecord(r, 'records[' + i + ']', seenPid, seenReplace));
    if (errors.length) die(5, 'soldier-replacements: ' + errors.length + ' schema error(s) in data/soldier-replacements.json:\n  ' + errors.join('\n  '));
  }
}

// 4g. WOMEN-IN-WAR PRESENTATION GATE (D153) — this additive card lane must never
// masquerade as a Soldier's Story replacement. Delegate to the canonical importer
// so the build and CLI enforce the same schema: no replacePid, no ss: ids, resolved
// codexRef links, and citation/dispute rules before the playable HTML is written.
{
  const p = join(ROOT, 'tools', 'import-women-in-war.mjs');
  if (existsSync(p)) {
    const chkWomen = spawnSync(process.execPath, [p], { cwd: ROOT, encoding: 'utf8' });
    if (chkWomen.status !== 0) {
      die(5, 'women-in-war: canonical validation failed:\n' + ((chkWomen.stderr || '') + (chkWomen.stdout || '')).trim());
    }
  }
}

// 4h. SAVE-SHAPE STRUCTURAL GATE (E41/D244) — structural enforcement of the architecture
// non-negotiable "save changes need a _SAVE_VER bump WITH idempotent lazy migration, or be purely
// additive". tools/save-shape.json records a whitespace-collapsed sha256/16 of every save-envelope-
// owning function (what is WRITTEN: serializeSave; what is ACCEPTED: loadLocal / importSave /
// _slValidSave + the E13 override pair; how it is APPLIED: applySave) plus the _SAVE_VER value. Any
// drift fails the build until the bump-or-additive decision is made consciously and the manifest is
// updated in the SAME commit — the diff on save-shape.json IS the audit trail. Purely additive
// changes (new fields riding INSIDE G.settings / G.campaign with lazy defaults) never touch these
// functions, so they pass untouched — exactly the additive path the law allows.
// HONEST COVERAGE LIMITS (D244 Opus panel): the gate watches DECLARED functions + the version mirror.
// It cannot see a brand-new persist path writing a different localStorage key, and it verifies the
// bump-vs-manifest half of the law, not that a migration actually shipped — those stay review
// territory. Assignment-form rebinding of the core envelope fns IS scanned (below). The extractor
// has no regex-literal state; enrolled functions must not grow regex literals containing braces or
// quotes (none do — a violation fails closed on the unbalanced-brace die).
{
  const SHAPE = join(ROOT, 'tools', 'save-shape.json');
  if (!existsSync(SHAPE)) die(5, 'save-shape: tools/save-shape.json is missing — the E41 structural gate needs the tracked manifest (see D244).');
  let shape; try { shape = JSON.parse(readFileSync(SHAPE, 'utf8')); } catch (e) { die(5, 'save-shape: tools/save-shape.json is invalid JSON: ' + e.message); }
  // extract a top-level `function NAME(...) {...}` body with string/comment-aware brace matching
  const extractFn = (text, name, where) => {
    const declRe = new RegExp('(^|\\n)\\s*function\\s+' + name + '\\s*\\(', 'g');
    const m = declRe.exec(text);
    if (!m) die(5, 'save-shape: function ' + name + ' not found in ' + where + ' — update tools/save-shape.json if it legitimately moved (a save-shape decision, D244).');
    // a SECOND same-name declaration in the same file would make the gate hash a dead copy while
    // the runtime uses the last declaration (D244 panel) — refuse the ambiguity outright
    if (declRe.exec(text)) die(5, 'save-shape: ' + name + ' is declared more than once in ' + where + ' — the gate cannot know which copy is live; keep one declaration per enrolled file.');
    const start = m.index + m[1].length;
    let i = text.indexOf('{', m.index + m[0].length);
    if (i < 0) die(5, 'save-shape: no body found for ' + name + ' in ' + where);
    let depth = 0, state = 'code';
    for (; i < text.length; i++) {
      const c = text[i], n = text[i + 1];
      if (state === 'code') {
        if (c === '/' && n === '/') { state = 'line'; i++; continue; }
        if (c === '/' && n === '*') { state = 'block'; i++; continue; }
        if (c === '"') { state = 'dq'; continue; }
        if (c === "'") { state = 'sq'; continue; }
        if (c === '`') { state = 'bq'; continue; }
        if (c === '{') depth++;
        else if (c === '}') { depth--; if (depth === 0) return text.slice(start, i + 1); }
      } else if (state === 'line') { if (c === '\n') state = 'code'; }
      else if (state === 'block') { if (c === '*' && n === '/') { state = 'code'; i++; } }
      else { // dq / sq / bq strings
        if (c === '\\') { i++; continue; }
        if ((state === 'dq' && c === '"') || (state === 'sq' && c === "'") || (state === 'bq' && c === '`')) state = 'code';
      }
    }
    die(5, 'save-shape: unbalanced braces extracting ' + name + ' from ' + where);
  };
  const sig = (txt) => createHash('sha256').update(txt.replace(/\s+/g, ' ').trim()).digest('hex').slice(0, 16);
  // _SAVE_VER value must match the manifest's saveVer (a bump must update the manifest in the same commit)
  const verMatch = /var\s+_SAVE_VER\s*=\s*(\d+)\s*;/.exec(base);
  if (!verMatch) die(5, 'save-shape: could not locate `var _SAVE_VER = <n>;` in build/base.html');
  const liveVer = Number(verMatch[1]);
  const problems = [];
  if (shape.saveVer !== liveVer) problems.push('_SAVE_VER is ' + liveVer + ' in build/base.html but tools/save-shape.json records saveVer ' + shape.saveVer + ' — a version bump must ship idempotent lazy migration AND update the manifest in the same commit.');
  const fileCache = new Map([['build/base.html', base]]);
  const readShapeFile = (rel) => {
    if (!fileCache.has(rel)) {
      const p = join(ROOT, rel);
      if (!existsSync(p)) die(5, 'save-shape: enrolled file ' + rel + ' is missing from the tree');
      fileCache.set(rel, readFileSync(p, 'utf8'));
    }
    return fileCache.get(rel);
  };
  const signatures = shape.signatures || {};
  // the manifest itself must stay armed: the core envelope owners can be re-pointed by a
  // conscious manifest edit (diff-visible) but never silently dropped to an empty scan
  for (const req of ['build/base.html::serializeSave', 'build/base.html::loadLocal', 'build/base.html::applySave']) {
    if (!(req in signatures)) problems.push('required signature "' + req + '" is missing from tools/save-shape.json — the gate cannot be disarmed by dropping its core entries.');
  }
  // assignment-form escape (D244 panel): a module rebinding a core envelope fn by EXPRESSION
  // (`applySave = function(){...}`) would bypass both the collision gate (no 2nd declaration) and
  // the hash pins above. Refuse it in src modules — envelope changes go through a declared,
  // manifest-enrolled override (the 105-save-guard pattern). importSave stays reassignable: the
  // shipped D234 wrapper in 91-save-slots.js uses exactly that idiom, and its accept SHAPE is
  // pinned separately via _slValidSave.
  {
    const REBIND = /(^|[^.\w'"])(serializeSave|loadLocal|applySave|saveLocal)\s*=(?![=])/;
    for (const f of modules) {
      const mline = readFileSync(join(SRC, f), 'utf8').match(REBIND);
      if (mline) problems.push('src/' + f + ' rebinds a core save-envelope function by assignment ("' + mline[0].trim() + '") — use a declared override enrolled in 00-manifest.json overrides + tools/save-shape.json instead.');
    }
  }
  for (const key of Object.keys(signatures)) {
    const [rel, fn] = key.split('::');
    if (!rel || !fn) { problems.push('malformed signature key "' + key + '" (expected <file>::<function>)'); continue; }
    const got = sig(extractFn(readShapeFile(rel), fn, rel));
    if (got !== signatures[key]) problems.push(key + ' changed (recorded ' + signatures[key] + ', computed ' + got + ').');
  }
  if (problems.length) die(5, 'SAVE-SHAPE GATE (E41/D244): the save envelope drifted from tools/save-shape.json:\n  ' + problems.join('\n  ')
    + '\n  The law: a save-shape change needs a _SAVE_VER bump WITH idempotent lazy migration, or must be purely additive'
    + ' (new fields inside settings/campaign with lazy defaults — those never trip this gate).'
    + ' Make that decision consciously, then update tools/save-shape.json with the computed value(s) above in the SAME commit.');
}

// ---- 5. report + write ----
const KB = (s) => (s.length / 1024).toFixed(1) + 'KB';
console.log('GATE OK · parse ✓ · hex ✓ · collision ✓ · no-fudge ✓ · citations ✓ · women-in-war ✓ · save-shape ✓');
console.log('  data:      GAME_DATA = {' + (dataKeys.join(', ') || '(none)') + '}');
console.log('  assets:    __ASSETS = ' + embedCount + ' embedded (' + (embedBytes / 1024).toFixed(0) + 'KB raw' + (embedCount ? '; ' + Object.keys(embedCats).map(c => c + ':' + embedCats[c]).join(', ') : '') + ')');
console.log('  modules:   ' + modules.join(', '));
console.log('  new fns:   ' + (newFns.map(x => x.name).join(', ') || '(none)'));
console.log('  overrides: ' + ([...overrides].join(', ') || '(none)') + ' (2x each ✓)');
console.log('  base ' + KB(base) + ' + inject ' + KB(inject) + ' = out ' + KB(out));

if (checkOnly) { console.log('--check: gates passed, NOT writing ' + OUT.split('/').pop()); process.exit(0); }
writeFileSync(OUT, out);
console.log('WROTE ' + OUT.split('/').pop() + ' (' + KB(out) + ')');
console.log('NEXT: node tools/bootprobe.mjs && node tools/t1probe.mjs && node tools/diag-classic.mjs');
