#!/usr/bin/env node
/* ===========================================================================
   tools/build.mjs — zero-dependency build for "The Civil War".

   Assembles the single shippable civil_war_generals.html from:
       build/base.html         the FROZEN foundation (Classic + Modern 3D + all
                               run-h chunks + the T1 War-Department layer) — a
                               byte-for-byte snapshot, NEVER edited by the build.
     + src/<modules>           the grand-strategy (owner-mode) work, authored as
                               ordered modules listed in src/00-manifest.json.

   The modules are concatenated (in manifest order) and spliced BEFORE the unique
   engine-end anchor in base.html (same contract as the legacy splice tool), so the
   anchor stays terminal and the last-def-wins override discipline holds.

   GATE-BEFORE-WRITE: the assembled HTML is gated IN MEMORY (extract <script> →
   `node --check` parse → invalid-hex grep → function-collision check). The
   deliverable civil_war_generals.html is overwritten ONLY if every gate passes,
   so a broken build can never corrupt the shipped file. Empirical/GPU probes
   (bootprobe, t1probe, diag-classic) run separately AFTER a successful build.

   Usage:  node tools/build.mjs            # build + gate
           node tools/build.mjs --check    # gate the assembled output, do NOT write
   Exit:   0 ok · 2 parse fail · 3 invalid-hex · 4 collision · 5 structural · 1 internal
   No external deps — node:fs / node:path / node:child_process only.
   =========================================================================== */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const BASE = join(ROOT, 'build', 'base.html');
const SRC = join(ROOT, 'src');
const OUT = join(ROOT, 'civil_war_generals.html');
const MANIFEST = join(SRC, '00-manifest.json');
// Build the anchor token at runtime so this source never contains a second copy.
const MARKER = '/*__ENGINE' + '_END__*/';
const HEX_BOMB = /0x[0-9a-fA-F]*[g-z]/;            // invalid hex literal -> parse bomb
const checkOnly = process.argv.includes('--check');

function die(code, msg) { console.error('BUILD FAIL [' + code + '] ' + msg); process.exit(code); }

// ---- 1. load base + assert the splice anchor is present and UNIQUE ----
if (!existsSync(BASE)) die(5, 'missing build/base.html (snapshot the frozen foundation first)');
const base = readFileSync(BASE, 'utf8');
const idx = base.indexOf(MARKER), last = base.lastIndexOf(MARKER);
if (idx < 0) die(5, 'MARKER_MISSING in base.html');
if (idx !== last) die(5, 'MARKER_NOT_UNIQUE in base.html');

// ---- 2. read manifest, concat ordered modules (per-module hex fail-fast) ----
const man = JSON.parse(readFileSync(MANIFEST, 'utf8'));
const modules = man.modules || [];
const overrides = new Set(man.overrides || []);   // function names allowed to appear 2x (base + override)
const newFns = [];                                 // brand-new top-level functions this build adds

let inject = '\n/* ====================================================================\n'
  + '   GENERATED by tools/build.mjs — base.html + data/*.json + src/*.js. DO NOT\n'
  + '   EDIT THIS FILE DIRECTLY; edit build/base.html, data/, or src/ and rebuild.\n'
  + '   ==================================================================== */\n';

// ---- 2a. inject data/*.json as a single GAME_DATA global (data-driven; one source of truth) ----
const DATA = join(ROOT, 'data');
let dataKeys = [];
if (existsSync(DATA)) {
  const dfiles = readdirSync(DATA).filter(f => f.endsWith('.json')).sort();
  const parts = [];
  for (const f of dfiles) {
    const raw = readFileSync(join(DATA, f), 'utf8');
    try { JSON.parse(raw); } catch (e) { die(5, 'invalid JSON in data/' + f + ': ' + e.message); }
    if (HEX_BOMB.test(raw)) die(3, 'invalid-hex literal in data/' + f);
    const key = f.replace(/\.json$/, '');
    parts.push(JSON.stringify(key) + ': ' + raw.trim());
    dataKeys.push(key);
  }
  if (parts.length) inject += '\n/* ===== data (build-injected from data/*.json) ===== */\nvar GAME_DATA = {\n' + parts.join(',\n') + '\n};\n';
}

// ---- 2b. inject assets/embed/** as a single __ASSETS global (D71 H1 ingestion pipeline) ----
// The OFFLINE tier: every file under assets/embed/<category>/ (the small, compressed,
// licence-vetted PD media produced by tools/prep-embed-assets.mjs) is Base64-inlined as a
// data: URL keyed "<category>/<basename-no-ext>". This is what makes the single-file deliverable
// portable: the in-game photo layer prefers __ASSETS (always present, offline) and upgrades to the
// relative-path hi-res (assets/<category>/) only when the file is served beside the assets folder.
// A HARD budget cap fails the build if the embed blob ever runs away (e.g. an un-compressed category)
// so the single file can never balloon unseen; SOFT warns earlier. Bump deliberately + log when a new
// (Aaron-approved) media category lands.
const EMBED = join(ROOT, 'assets', 'embed');
const EMBED_SOFT = 1.5 * 1024 * 1024;     // warn beyond ~1.5MB raw
const EMBED_HARD = 3.0 * 1024 * 1024;     // FAIL beyond ~3.0MB raw (runaway guard; raise + log when footage/scenes land)
const MIME = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp',
               '.gif': 'image/gif', '.svg': 'image/svg+xml', '.mp4': 'video/mp4', '.webm': 'video/webm' };
let embedBytes = 0, embedCount = 0;
const embedCats = {};
if (existsSync(EMBED)) {
  const aparts = [];
  const seenKeys = new Map();   // __ASSETS key -> source file (dup-key collision gate)
  for (const cat of readdirSync(EMBED, { withFileTypes: true }).filter(d => d.isDirectory()).sort((a, b) => a.name < b.name ? -1 : 1)) {
    const cdir = join(EMBED, cat.name);
    // withFileTypes so a stray sub-DIRECTORY named like an asset (e.g. foo.jpg/) is skipped, not
    // readFileSync'd into an uncaught EISDIR crash (bug-hunt FINDER#2).
    for (const ent of readdirSync(cdir, { withFileTypes: true }).filter(e => e.isFile() && e.name[0] !== '.').sort((a, b) => a.name < b.name ? -1 : 1)) {
      const f = ent.name;
      const ext = (f.match(/\.[^.]+$/) || [''])[0].toLowerCase();
      const mime = MIME[ext];
      if (!mime) die(5, 'embed: unsupported asset type ' + cat.name + '/' + f + ' (extend MIME[] in build.mjs to allow it)');
      const key = cat.name + '/' + f.replace(/\.[^.]+$/, '');
      // two sources differing only by extension (lee.jpg + lee.png) would collide to one key; the
      // last would silently win. Fail loudly instead (bug-hunt FINDER#2).
      if (seenKeys.has(key)) die(5, 'embed: duplicate __ASSETS key "' + key + '" from ' + cat.name + '/' + f + ' (collides with ' + seenKeys.get(key) + ') — two source files differ only by extension; rename or remove one.');
      seenKeys.set(key, cat.name + '/' + f);
      const buf = readFileSync(join(cdir, f));
      embedBytes += buf.length; embedCount++;
      embedCats[cat.name] = (embedCats[cat.name] || 0) + 1;
      aparts.push(JSON.stringify(key) + ':"data:' + mime + ';base64,' + buf.toString('base64') + '"');
    }
  }
  if (embedBytes > EMBED_HARD) die(5, 'embed BUDGET: assets/embed/ is ' + (embedBytes / 1048576).toFixed(2) + 'MB raw, over the ' + (EMBED_HARD / 1048576).toFixed(1) + 'MB hard cap — compress harder (tools/prep-embed-assets.mjs) or raise EMBED_HARD deliberately (and log why).');
  if (embedBytes > EMBED_SOFT) console.warn('  [embed] WARNING: ' + (embedBytes / 1048576).toFixed(2) + 'MB raw embed tier, over the ' + (EMBED_SOFT / 1048576).toFixed(1) + 'MB soft budget — consider compressing the tier (tools/prep-embed-assets.mjs).');
  if (aparts.length) inject += '\n/* ===== embedded assets (build-injected from assets/embed/**; offline tier) ===== */\nvar __ASSETS = {\n' + aparts.join(',\n') + '\n};\n';
}
// guarantee the bare-name global always exists so modules can read it unconditionally (no embed dir → {})
if (embedCount === 0) inject += '\n/* ===== embedded assets: none on disk; declare the empty global ===== */\nvar __ASSETS = {};\n';

for (const f of modules) {
  const p = join(SRC, f);
  if (!existsSync(p)) die(5, 'manifest lists missing module: ' + f);
  const txt = readFileSync(p, 'utf8');
  if (HEX_BOMB.test(txt)) die(3, 'invalid-hex literal in module ' + f);
  // collect top-level `function NAME(` declarations this module introduces
  const re = /(^|\n)\s*function\s+([A-Za-z_$][\w$]*)\s*\(/g;
  let m; while ((m = re.exec(txt))) { if (!overrides.has(m[2])) newFns.push({ name: m[2], file: f }); }
  inject += '\n/* ===== module: ' + f + ' ===== */\n' + txt + '\n';
}

// ---- 3. assemble in memory (marker stays terminal) ----
const out = base.slice(0, idx) + inject + base.slice(idx);

// ---- 4. GATE the assembled output (in memory) ----
const so = out.indexOf('<script>'), sc = out.indexOf('</script>');
if (so < 0 || sc < 0 || sc < so) die(5, 'could not locate a single <script>..</script> pair');
const body = out.slice(so + '<script>'.length, sc);

// 4a. parse gate
const tmp = join(tmpdir(), 'gor_build_check.js');
writeFileSync(tmp, body);
const chk = spawnSync(process.execPath, ['--check', tmp], { encoding: 'utf8' });
if (chk.status !== 0) die(2, 'node --check failed:\n' + (chk.stderr || chk.stdout || '').trim());

// 4b. invalid-hex gate (whole script body). The HEX_BOMB heuristic catches an invalid hex LITERAL
// (e.g. 0x1g) in CODE — which can never appear inside a "data:...;base64,..." string literal. The
// embedded-asset blob (__ASSETS, H1/D71) is megabytes of base64 string content that textually trips
// the naive pattern (a "0x"+hex+[g-z] run is near-certain in any large base64), so mask data: URL
// string literals before this scan. Parseability of the WHOLE body is already proven by 4a
// (node --check), so masking string CONTENT here loses no real coverage. (Also covers future video
// data: URLs for H2 footage.)
const hexScan = body.replace(/"data:[^"]*"/g, '""');
if (HEX_BOMB.test(hexScan)) die(3, 'invalid-hex literal in assembled <script>');

// 4c. collision gate — new functions must appear exactly once; overrides exactly twice
const countFn = (name) => {
  const r = new RegExp('(^|\\n)\\s*function\\s+' + name.replace(/[$]/g, '\\$') + '\\s*\\(', 'g');
  return (body.match(r) || []).length;
};
for (const { name, file } of newFns) {
  const n = countFn(name);
  if (n !== 1) die(4, 'collision: new function ' + name + ' (' + file + ') defined ' + n + 'x (expected 1; rename or add to manifest.overrides)');
}
for (const name of overrides) {
  const n = countFn(name);
  if (n !== 2) die(4, 'override ' + name + ' defined ' + n + 'x (expected 2: base + override)');
}

// 4d. NO-FUDGE OUTPUT WALL (D74/D94 R-3) — the rating / badge module may only READ unit fields and
// RETURN factors; it must NEVER write a casualty count, a winner, unit strength, or an out-of-band
// sev.* at resolution time (the scripted "higher rating => auto-win" hack). Enforced STRUCTURALLY so
// the invariant cannot be eroded by a later increment. The combat modules (T0 etc.) legitimately write
// these — the wall scopes to the rating/badge module(s), which exist only to seed inputs.
// D105 (bug-hunt): 35-command.js carries the STRATEGIC rating code now (the dev-trait reputation-shaping —
// cmdOnResolve / _cmdDevTrait / _cmdAttritionDrag), which also only seeds an INPUT (reputation) and must never
// write the scoreboard. It writes solely command state (reputation/seniority/capital/devTrack), none of which
// match the forbidden set, so scoping the same wall over it closes the no-fudge coverage gap.
const RATING_MODULES = ['tactical/T14-ratings.js', '35-command.js', 'tactical/T15-oob.js'];   // D106: T15-oob = the OOB-mapping read-out (pure read; scanned so a future edit can't add a scoreboard write unseen)
const NO_FUDGE_FORBIDDEN = [
  { re: /\b(cas|aCas|bCas)\s*(\+=|-=|=)(?!=)/, what: 'a casualty count (cas/aCas/bCas)' },
  { re: /\.victory\s*=(?!=)/, what: 'the victory result (.victory)' },
  { re: /\.men\s*(\+=|-=|=)(?!=)/, what: 'unit strength (.men)' },
  { re: /\bsev\.[A-Za-z_$][\w$]*\s*=(?!=)/, what: 'a severity lever (sev.*) out of band' },
  // bracket-notation variants — close the computed-member bypass (u["men"]=0 etc.) so the wall cannot be
  // eroded by a later increment writing the scoreboard via brackets (R-3 bug-hunt hardening). A full AST scan
  // would also catch aliasing; this fast textual pass covers the direct bracket forms.
  { re: /\[\s*['"](?:men|cas|aCas|bCas|victory)['"]\s*\]\s*(\+=|-=|=)(?!=)/, what: 'a scoreboard field via bracket notation (["men"]/["victory"]/["cas"]…)' },
  { re: /\bsev\s*\[\s*['"][^'"]+['"]\s*\]\s*(\+=|-=|=)(?!=)/, what: 'a severity lever via bracket notation (sev["…"])' },
];
for (const rm of RATING_MODULES) {
  const rp = join(SRC, rm);
  if (!existsSync(rp)) continue;
  const rsrc = readFileSync(rp, 'utf8');
  for (const f of NO_FUDGE_FORBIDDEN) {
    const m = rsrc.match(f.re);
    if (m) die(5, 'no-fudge OUTPUT-WALL: ' + rm + ' writes ' + f.what + ' ("' + m[0].trim() + '") — the rating/badge layer may only SEED inputs + RETURN factors, never write the scoreboard at resolution time (D74/D94).');
  }
}

// 4e. CITATION-PROVENANCE GATE (D92/D103) — the citation-grade, anti-Lost-Cause non-negotiable enforced
// STRUCTURALLY: any record stamped prov/provenance:"Verified" MUST carry >=2 sources. Honest history means
// an authored claim either has >=2 independent citations (Verified) or is downgraded to Inferred/Disputed —
// never a "Verified" stamp resting on 0-1 sources. Scans every data/*.json recursively so the rule cannot be
// eroded by a later record anywhere in the catalog (mirrors the 4d no-fudge wall: a non-negotiable made
// un-erodable by the build itself).
{
  const offenders = [];
  const SRC_KEYS = ['sources', 'src'];
  const walk = (node, file, trail) => {
    if (Array.isArray(node)) { node.forEach((v, i) => walk(v, file, trail + '[' + i + ']')); return; }
    if (node && typeof node === 'object') {
      // match BOTH keys independently (so an Inferred `prov` can't mask a Verified `provenance`), and
      // normalize trim+case so a bare stamp of "Verified " / "verified" / "VERIFIED" cannot evade. The
      // long descriptive forms ("Verified specs (…)", "Verified (high) — …") trim-lowercase to something
      // other than exactly "verified", so they stay out of the structured-source gate by design (their
      // citations live inline in the prose) — R-6 bug-hunt hardening, D103.
      const norm = (v) => (typeof v === 'string' ? v.trim().toLowerCase() : '');
      const isVerified = norm(node.prov) === 'verified' || norm(node.provenance) === 'verified';
      if (isVerified) {
        let sc = 0;
        for (const k of SRC_KEYS) { if (Array.isArray(node[k])) { sc = node[k].length; break; } }
        if (sc < 2) {
          const id = node.key || node.name || node.id || node.label || trail || '(record)';
          offenders.push(file + ' :: ' + id + ' (Verified, ' + sc + ' source' + (sc === 1 ? '' : 's') + ')');
        }
      }
      for (const k in node) walk(node[k], file, trail ? trail + '.' + k : k);
    }
  };
  if (existsSync(DATA)) {
    for (const f of readdirSync(DATA).filter(f => f.endsWith('.json')).sort()) {
      let j; try { j = JSON.parse(readFileSync(join(DATA, f), 'utf8')); } catch (e) { continue; } // JSON already gated in 2a
      walk(j, 'data/' + f, '');
    }
  }
  if (offenders.length) die(5, 'citation-provenance: ' + offenders.length + ' record(s) stamped "Verified" with <2 sources (the >=2-source non-negotiable, D92/D103) — add a second independent REAL source or downgrade prov to "Inferred"/"Disputed":\n  ' + offenders.join('\n  '));
}

// ---- 5. report + write ----
const KB = (s) => (s.length / 1024).toFixed(1) + 'KB';
console.log('GATE OK · parse ✓ · hex ✓ · collision ✓ · no-fudge ✓ · citations ✓');
console.log('  data:      GAME_DATA = {' + (dataKeys.join(', ') || '(none)') + '}');
console.log('  assets:    __ASSETS = ' + embedCount + ' embedded (' + (embedBytes / 1024).toFixed(0) + 'KB raw' + (embedCount ? '; ' + Object.keys(embedCats).map(c => c + ':' + embedCats[c]).join(', ') : '') + ')');
console.log('  modules:   ' + modules.join(', '));
console.log('  new fns:   ' + (newFns.map(x => x.name).join(', ') || '(none)'));
console.log('  overrides: ' + ([...overrides].join(', ') || '(none)') + ' (2x each ✓)');
console.log('  base ' + KB(base) + ' + inject ' + KB(inject) + ' = out ' + KB(out));

if (checkOnly) { console.log('--check: gates passed, NOT writing ' + OUT.split('/').pop()); process.exit(0); }
writeFileSync(OUT, out);
console.log('WROTE ' + OUT.split('/').pop() + ' (' + KB(out) + ')');
console.log('NEXT: node tools/bootprobe.mjs && node tools/t1probe.mjs && node tools/diag-classic.mjs');
